### ISSUE TITLE
Token should work with sharing site set to same hostname

### ISSUE THREAD

**Issue by tombola** [tombola/wagtail-sharing#3]
When using `/share/<jwt-token>` there is no overlap between the urls accessible at the sharing site and those of the normal site, so the sharing site should be able to use the same hostname.

This worked when tested locally (not verified) but not when deployed in a project on heroku for some reason, assume something project specific but would like to check/resolve before submitting PR back to cfpb repo.

**Comment by zerolab** [comment]
issue describe in https://github.com/tombola/wagtail-sharing/pull/1#discussion_r466059906. this can be closed
